import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "./(components)/Header";

const roboto = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        <div className="mx-[1rem] sm:mx-[2rem] lg:mx-[10rem] h-[85vh]">{children}</div>
      </body>
    </html>
  );
}
